application: canvas-epigram-758
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.php

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

  # Serve mmdb as static resources.
- url: /MMDB/(.*\.(mmdb))$
  static_files: MMDB/\1
  upload: MMDB/.*\.(mmdb)$
  application_readable: true